FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf

FROM node:latest
WORKDIR /app
RUN mkdir /app/uploads
COPY ./app/package*.json ./
RUN npm install
# copy the entire app over
COPY ./app /app
# make sure the init script is copied over
COPY ./app/docker-entrypoint-initdb.d/mongo-init.js /app/docker-entrypoint-initdb.d/mongo-init.js
# expose a port for mongodb (for devcelopment)
EXPOSE 27017
EXPOSE 3000
CMD ["npm", "start"]
# not sure about this one
# USER node
