FROM nginx:latest
# RUN mkdir /app
# COPY ./app/app.js /app
# EXPOSE 3000
COPY nginx.conf /etc/nginx/nginx.conf

# FROM node:latest
# WORKDIR /app
# COPY app/package.json /app
# RUN npm install
# COPY ./app /app
# EXPOSE 3000
# CMD ["npm", "start"]
# USER node

FROM node:latest
# WORKDIR /usr/src/app
WORKDIR /app
RUN mkdir /app/uploads
COPY ./app/package*.json ./
RUN npm install
COPY ./app /app
# COPY ./app/.env /app/.env
COPY ./app/docker-entrypoint-initdb.d/mongo-init.js /app/docker-entrypoint-initdb.d/mongo-init.js
# EXPOSE 2020
EXPOSE 27017
EXPOSE 3000
CMD ["npm", "start"]
# USER node
