version: '2.2'
services:
  app:
    container_name: imageHost-container
    restart: always
    environment: 
        # ! Change this to your domain name
        VIRTUAL_HOST: DOMAIN.COM
    expose: .
    expose:
      - 80
    links:
      - mongo
    volumes:
      # map /tmp/logs in the container to logs on host
      - ./logs:/usr/src/app/logs
  mongo:
    container_name: mongo
    image: mongo
    environment:
        - Mongo_INITDB_DATABASE=imageHost
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=rhinos
    volumes:
        # For the startup script that mongo runs to create a new user
        - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        # Store the mongo database on the host to make it persistent between container restarts
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'
    command: mongod --auth --quiet